name: conditional_statement_if_testing
on: push
jobs:
  checking:
    runs-on: ubuntu-22.04
    steps:
      - name: testing by akash
        run: echo 'building the project'
      - name: one more testing
        if: github.ref == 'refs/head/master'
        run: echo 'deploying the job'
