name: greeting workflow
on: push
jobs:
  job1_greetAkash:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting Akash
        run: echo "Hello Akash! How are you?"
  job2_greetAanchal:
    needs: job1_greetAkash
    runs-on: ubuntu-latest
    steps:
      - name: now greeting Aanchal
        run: echo "Hello, Mrs. Gupta! How are you?"
